namespace App.Web.Helpers
{
    public static class HelperCountry
    {
        public sealed record Country(string IsoCode, string NameEn, string NameTr);

        public static readonly IReadOnlyList<Country> GetAll = new Country[]
        {
            new("AF", "Afghanistan",                      "Afganistan"),
            new("AL", "Albania",                          "Arnavutluk"),
            new("DZ", "Algeria",                          "Cezayir"),
            new("AD", "Andorra",                          "Andorra"),
            new("AO", "Angola",                           "Angola"),
            new("AG", "Antigua and Barbuda",              "Antigua ve Barbuda"),
            new("AR", "Argentina",                        "Arjantin"),
            new("AM", "Armenia",                          "Ermenistan"),
            new("AU", "Australia",                        "Avustralya"),
            new("AT", "Austria",                          "Avusturya"),
            new("AZ", "Azerbaijan",                       "Azerbaycan"),
            new("BS", "Bahamas",                          "Bahamalar"),
            new("BH", "Bahrain",                          "Bahreyn"),
            new("BD", "Bangladesh",                       "Bangladeş"),
            new("BB", "Barbados",                         "Barbados"),
            new("BY", "Belarus",                          "Belarus"),
            new("BE", "Belgium",                          "Belçika"),
            new("BZ", "Belize",                           "Belize"),
            new("BJ", "Benin",                            "Benin"),
            new("BT", "Bhutan",                           "Butan"),
            new("BO", "Bolivia",                          "Bolivya"),
            new("BA", "Bosnia and Herzegovina",           "Bosna-Hersek"),
            new("BW", "Botswana",                         "Botsvana"),
            new("BR", "Brazil",                           "Brezilya"),
            new("BN", "Brunei",                           "Brunei"),
            new("BG", "Bulgaria",                         "Bulgaristan"),
            new("BF", "Burkina Faso",                     "Burkina Faso"),
            new("BI", "Burundi",                          "Burundi"),
            new("CV", "Cape Verde",                       "Cabo Verde"),
            new("KH", "Cambodia",                         "Kamboçya"),
            new("CM", "Cameroon",                         "Kamerun"),
            new("CA", "Canada",                           "Kanada"),
            new("CF", "Central African Republic",         "Orta Afrika Cumhuriyeti"),
            new("TD", "Chad",                             "Çad"),
            new("CL", "Chile",                            "Şili"),
            new("CN", "China",                            "Çin"),
            new("CO", "Colombia",                         "Kolombiya"),
            new("KM", "Comoros",                          "Komorlar"),
            new("CG", "Congo",                            "Kongo"),
            new("CD", "DR Congo",                         "Kongo Demokratik Cumhuriyeti"),
            new("CR", "Costa Rica",                       "Kosta Rika"),
            new("HR", "Croatia",                          "Hırvatistan"),
            new("CU", "Cuba",                             "Küba"),
            new("CY", "Cyprus",                           "Kıbrıs"),
            new("CZ", "Czech Republic",                   "Çekya"),
            new("DK", "Denmark",                          "Danimarka"),
            new("DJ", "Djibouti",                         "Cibuti"),
            new("DM", "Dominica",                         "Dominika"),
            new("DO", "Dominican Republic",               "Dominik Cumhuriyeti"),
            new("EC", "Ecuador",                          "Ekvador"),
            new("EG", "Egypt",                            "Mısır"),
            new("SV", "El Salvador",                      "El Salvador"),
            new("GQ", "Equatorial Guinea",                "Ekvator Ginesi"),
            new("ER", "Eritrea",                          "Eritre"),
            new("EE", "Estonia",                          "Estonya"),
            new("SZ", "Eswatini",                         "Esvatini"),
            new("ET", "Ethiopia",                         "Etiyopya"),
            new("FJ", "Fiji",                             "Fiji"),
            new("FI", "Finland",                          "Finlandiya"),
            new("FR", "France",                           "Fransa"),
            new("GA", "Gabon",                            "Gabon"),
            new("GM", "Gambia",                           "Gambiya"),
            new("GE", "Georgia",                          "Gürcistan"),
            new("DE", "Germany",                          "Almanya"),
            new("GH", "Ghana",                            "Gana"),
            new("GR", "Greece",                           "Yunanistan"),
            new("GD", "Grenada",                          "Grenada"),
            new("GT", "Guatemala",                        "Guatemala"),
            new("GN", "Guinea",                           "Gine"),
            new("GW", "Guinea-Bissau",                    "Gine-Bissau"),
            new("GY", "Guyana",                           "Guyana"),
            new("HT", "Haiti",                            "Haiti"),
            new("HN", "Honduras",                         "Honduras"),
            new("HU", "Hungary",                          "Macaristan"),
            new("IS", "Iceland",                          "İzlanda"),
            new("IN", "India",                            "Hindistan"),
            new("ID", "Indonesia",                        "Endonezya"),
            new("IR", "Iran",                             "İran"),
            new("IQ", "Iraq",                             "Irak"),
            new("IE", "Ireland",                          "İrlanda"),
            new("IL", "Israel",                           "İsrail"),
            new("IT", "Italy",                            "İtalya"),
            new("JM", "Jamaica",                          "Jamaika"),
            new("JP", "Japan",                            "Japonya"),
            new("JO", "Jordan",                           "Ürdün"),
            new("KZ", "Kazakhstan",                       "Kazakistan"),
            new("KE", "Kenya",                            "Kenya"),
            new("KI", "Kiribati",                         "Kiribati"),
            new("KW", "Kuwait",                           "Kuveyt"),
            new("KG", "Kyrgyzstan",                       "Kırgızistan"),
            new("LA", "Laos",                             "Laos"),
            new("LV", "Latvia",                           "Letonya"),
            new("LB", "Lebanon",                          "Lübnan"),
            new("LS", "Lesotho",                          "Lesoto"),
            new("LR", "Liberia",                          "Liberya"),
            new("LY", "Libya",                            "Libya"),
            new("LI", "Liechtenstein",                    "Lihtenştayn"),
            new("LT", "Lithuania",                        "Litvanya"),
            new("LU", "Luxembourg",                       "Lüksemburg"),
            new("MG", "Madagascar",                       "Madagaskar"),
            new("MW", "Malawi",                           "Malavi"),
            new("MY", "Malaysia",                         "Malezya"),
            new("MV", "Maldives",                         "Maldivler"),
            new("ML", "Mali",                             "Mali"),
            new("MT", "Malta",                            "Malta"),
            new("MH", "Marshall Islands",                 "Marshall Adaları"),
            new("MR", "Mauritania",                       "Moritanya"),
            new("MU", "Mauritius",                        "Mauritius"),
            new("MX", "Mexico",                           "Meksika"),
            new("FM", "Micronesia",                       "Mikronezya"),
            new("MD", "Moldova",                          "Moldova"),
            new("MC", "Monaco",                           "Monako"),
            new("MN", "Mongolia",                         "Moğolistan"),
            new("ME", "Montenegro",                       "Karadağ"),
            new("MA", "Morocco",                          "Fas"),
            new("MZ", "Mozambique",                       "Mozambik"),
            new("MM", "Myanmar",                          "Myanmar"),
            new("NA", "Namibia",                          "Namibya"),
            new("NR", "Nauru",                            "Nauru"),
            new("NP", "Nepal",                            "Nepal"),
            new("NL", "Netherlands",                      "Hollanda"),
            new("NZ", "New Zealand",                      "Yeni Zelanda"),
            new("NI", "Nicaragua",                        "Nikaragua"),
            new("NE", "Niger",                            "Nijer"),
            new("NG", "Nigeria",                          "Nijerya"),
            new("KP", "North Korea",                      "Kuzey Kore"),
            new("MK", "North Macedonia",                  "Kuzey Makedonya"),
            new("NO", "Norway",                           "Norveç"),
            new("OM", "Oman",                             "Umman"),
            new("PK", "Pakistan",                         "Pakistan"),
            new("PW", "Palau",                            "Palau"),
            new("PS", "Palestine",                        "Filistin"),
            new("PA", "Panama",                           "Panama"),
            new("PG", "Papua New Guinea",                 "Papua Yeni Gine"),
            new("PY", "Paraguay",                         "Paraguay"),
            new("PE", "Peru",                             "Peru"),
            new("PH", "Philippines",                      "Filipinler"),
            new("PL", "Poland",                           "Polonya"),
            new("PT", "Portugal",                         "Portekiz"),
            new("QA", "Qatar",                            "Katar"),
            new("RO", "Romania",                          "Romanya"),
            new("RU", "Russia",                           "Rusya"),
            new("RW", "Rwanda",                           "Ruanda"),
            new("KN", "Saint Kitts and Nevis",            "Saint Kitts ve Nevis"),
            new("LC", "Saint Lucia",                      "Saint Lucia"),
            new("VC", "Saint Vincent and the Grenadines", "Saint Vincent ve Grenadinler"),
            new("WS", "Samoa",                            "Samoa"),
            new("SM", "San Marino",                       "San Marino"),
            new("ST", "São Tomé and Príncipe",            "São Tomé ve Príncipe"),
            new("SA", "Saudi Arabia",                     "Suudi Arabistan"),
            new("SN", "Senegal",                          "Senegal"),
            new("RS", "Serbia",                           "Sırbistan"),
            new("SC", "Seychelles",                       "Seyşeller"),
            new("SL", "Sierra Leone",                     "Sierra Leone"),
            new("SG", "Singapore",                        "Singapur"),
            new("SK", "Slovakia",                         "Slovakya"),
            new("SI", "Slovenia",                         "Slovenya"),
            new("SB", "Solomon Islands",                  "Solomon Adaları"),
            new("SO", "Somalia",                          "Somali"),
            new("ZA", "South Africa",                     "Güney Afrika"),
            new("KR", "South Korea",                      "Güney Kore"),
            new("SS", "South Sudan",                      "Güney Sudan"),
            new("ES", "Spain",                            "İspanya"),
            new("LK", "Sri Lanka",                        "Sri Lanka"),
            new("SD", "Sudan",                            "Sudan"),
            new("SR", "Suriname",                         "Surinam"),
            new("SE", "Sweden",                           "İsveç"),
            new("CH", "Switzerland",                      "İsviçre"),
            new("SY", "Syria",                            "Suriye"),
            new("TW", "Taiwan",                           "Tayvan"),
            new("TJ", "Tajikistan",                       "Tacikistan"),
            new("TZ", "Tanzania",                         "Tanzanya"),
            new("TH", "Thailand",                         "Tayland"),
            new("TL", "Timor-Leste",                      "Timor-Leste"),
            new("TG", "Togo",                             "Togo"),
            new("TO", "Tonga",                            "Tonga"),
            new("TT", "Trinidad and Tobago",              "Trinidad ve Tobago"),
            new("TN", "Tunisia",                          "Tunus"),
            new("TR", "Turkey",                           "Türkiye"),
            new("TM", "Turkmenistan",                     "Türkmenistan"),
            new("TV", "Tuvalu",                           "Tuvalu"),
            new("UG", "Uganda",                           "Uganda"),
            new("UA", "Ukraine",                          "Ukrayna"),
            new("AE", "United Arab Emirates",             "Birleşik Arap Emirlikleri"),
            new("GB", "United Kingdom",                   "Birleşik Krallık"),
            new("US", "United States",                    "Amerika Birleşik Devletleri"),
            new("UY", "Uruguay",                          "Uruguay"),
            new("UZ", "Uzbekistan",                       "Özbekistan"),
            new("VU", "Vanuatu",                          "Vanuatu"),
            new("VE", "Venezuela",                        "Venezuela"),
            new("VN", "Vietnam",                          "Vietnam"),
            new("YE", "Yemen",                            "Yemen"),
            new("ZM", "Zambia",                           "Zambiya"),
            new("ZW", "Zimbabwe",                         "Zimbabve"),
        };
    }
}
